// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Sumo Logic and manual
//     changes will be clobbered when the file is regenerated. Do not submit
//     changes to this file.
//
// ----------------------------------------------------------------------------
package sumologic

import (
	"github.com/hashicorp/terraform-plugin-sdk/helper/schema"
	"log"
)

func resourceSumologicRole() *schema.Resource {
	return &schema.Resource{
		Create: resourceSumologicRoleCreate,
		Read:   resourceSumologicRoleRead,
		Update: resourceSumologicRoleUpdate,
		Delete: resourceSumologicRoleDelete,
		Importer: &schema.ResourceImporter{
			State: schema.ImportStatePassthrough,
		},

		Schema: map[string]*schema.Schema{
			"name": {
				Type:     schema.TypeString,
				Required: true,
				ForceNew: false,
			},
			"description": {
				Type:     schema.TypeString,
				Optional: true,
				ForceNew: false,
			},
			"capabilities": {
				Type:     schema.TypeList,
				Optional: true,
				ForceNew: false,

				Elem: &schema.Schema{
					Type: schema.TypeString,
				},
			},
			"filter_predicate": {
				Type:     schema.TypeString,
				Optional: true,
				ForceNew: false,
			},
		},
	}
}

func resourceSumologicRoleRead(d *schema.ResourceData, meta interface{}) error {
	c := meta.(*Client)

	id := d.Id()
	role, err := c.GetRole(id)

	if err != nil {
		return err
	}

	if role == nil {
		log.Printf("[WARN] Role not found, removing from state: %v - %v", id, err)
		d.SetId("")
		return nil
	}

	d.Set("name", role.Name)
	d.Set("description", role.Description)
	d.Set("capabilities", role.Capabilities)
	d.Set("filter_predicate", role.FilterPredicate)

	return nil
}
func resourceSumologicRoleDelete(d *schema.ResourceData, meta interface{}) error {
	c := meta.(*Client)

	return c.DeleteRole(d.Id())
}

func resourceSumologicRoleUpdate(d *schema.ResourceData, meta interface{}) error {
	c := meta.(*Client)

	role := resourceToRole(d)

	err := c.UpdateRole(role)

	if err != nil {
		return err
	}

	return resourceSumologicRoleRead(d, meta)
}

func resourceSumologicRoleCreate(d *schema.ResourceData, meta interface{}) error {
	c := meta.(*Client)

	if d.Id() == "" {
		role := resourceToRole(d)
		id, err := c.CreateRole(role)

		if err != nil {
			return err
		}

		d.SetId(id)
	}

	return resourceSumologicRoleRead(d, meta)
}
func resourceToRole(d *schema.ResourceData) Role {
	rawCapabilities := d.Get("capabilities").([]interface{})
	capabilities := make([]string, len(rawCapabilities))
	for i, v := range rawCapabilities {
		capabilities[i] = v.(string)
	}

	return Role{
		Name:            d.Get("name").(string),
		ID:              d.Id(),
		Description:     d.Get("description").(string),
		FilterPredicate: d.Get("filter_predicate").(string),
		Capabilities:    capabilities,
	}
}
