// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Sumo Logic and manual
//     changes will be clobbered when the file is regenerated. Do not submit
//     changes to this file.
//
// ----------------------------------------------------------------------------\
package sumologic

import (
	"log"

	"github.com/hashicorp/terraform-plugin-sdk/helper/schema"
)

func resourceSumologicMonitor() *schema.Resource {
	return &schema.Resource{
		Create: resourceSumologicMonitorCreate,
		Read:   resourceSumologicMonitorRead,
		Update: resourceSumologicMonitorUpdate,
		Delete: resourceSumologicMonitorDelete,
		Importer: &schema.ResourceImporter{
			State: schema.ImportStatePassthrough,
		},

		Schema: map[string]*schema.Schema{
			"name": {
				Type:     schema.TypeString,
				Required: true,
				ForceNew: false,
			},
			"scope": {
				Type:     schema.TypeString,
				Required: true,
				ForceNew: false,
			},
			"parse_expression": {
				Type:     schema.TypeString,
				Required: true,
				ForceNew: false,
			},
			"enabled": {
				Type:     schema.TypeBool,
				Required: true,
				ForceNew: false,
			},
		},
	}
}

func resourceSumologicMonitorRead(d *schema.ResourceData, meta interface{}) error {
	c := meta.(*Client)

	id := d.Id()
	monitor, err := c.GetMonitor(id)

	if err != nil {
		return err
	}

	if monitor == nil {
		log.Printf("[WARN] Monitor not found, removing from state: %v - %v", id, err)
		d.SetId("")
		return nil
	}

	d.Set("name", monitor.Name)
	d.Set("scope", monitor.Scope)
	d.Set("parse_expression", monitor.ParseExpression)
	d.Set("enabled", monitor.Enabled)

	return nil
}

func resourceSumologicMonitorDelete(d *schema.ResourceData, meta interface{}) error {
	c := meta.(*Client)
	return c.DeleteMonitor(d.Id())
}

func resourceSumologicMonitorCreate(d *schema.ResourceData, meta interface{}) error {
	c := meta.(*Client)

	if d.Id() == "" {
		monitor := resourceToMonitor(d)
		id, err := c.CreateMonitor(monitor)

		if err != nil {
			return err
		}

		d.SetId(id)
	}

	return resourceSumologicMonitorRead(d, meta)
}

func resourceSumologicMonitorUpdate(d *schema.ResourceData, meta interface{}) error {
	c := meta.(*Client)

	monitor := resourceToMonitor(d)

	err := c.UpdateMonitor(monitor)

	if err != nil {
		return err
	}

	return resourceSumologicMonitorRead(d, meta)
}

func resourceToMonitor(d *schema.ResourceData) Monitor {

	return Monitor{
		ID:              d.Id(),
		Name:            d.Get("name").(string),
		Scope:           d.Get("scope").(string),
		ParseExpression: d.Get("parse_expression").(string),
		Enabled:         d.Get("enabled").(bool),
	}
}
